
# Snakey Keylogger - Development Notes (26/02/2025)

## Purpose
The main purpose of this script is to collect **system information**, **clipboard data**, **keyboard inputs** (via keylogger), **audio recordings**, and **screenshots**. It then **encrypts** these logs and sends them via **email** to a predefined address.

---

## Keylogger Implementation
The keylogger captures key inputs via the **pynput** library. It also:
- Periodically takes **screenshots** every 30 seconds.
- Records **audio** for 10 seconds.
- Copies **clipboard** data.

---

## Encryption
The data (logs) generated by the script are **encrypted** using the `cryptography.fernet` module, ensuring sensitive data is protected when sent over email.

---

## Email Sending
The encrypted logs are sent via **Gmail’s SMTP server** (`smtp.gmail.com`) with **SSL encryption**. It uses an **app-specific password** for authentication.

---

## Logging Information
System information, including:
- Public/Private IP addresses
- Machine specifications
- Hostname

This information is saved to a file. Logs also include **timestamps** to track the duration of data collection.

---

## Error Handling
There are error handling mechanisms in place for:
- **Sending emails**
- **Accessing clipboard data**

These mechanisms ensure that if any step fails, the error is logged without crashing the script.

---

## Libraries Used
External libraries used in this project include:

- `pynput` for capturing keyboard inputs.
- `win32clipboard` for clipboard access.
- `sounddevice` & `scipy.io.wavfile` for audio recording.
- `PIL` (Python Imaging Library) for taking screenshots.
- `cryptography` for encrypting and decrypting logs.
- `requests` for retrieving the public IP address of the system.
- `smtplib` for sending emails securely via SMTP.

---

## Security Note
Ensure that the **app password** used for the Gmail account is **secure** and **never hardcoded** into production scripts. In a real-world scenario, it should be retrieved from an environment variable or a **secure vault**.
